import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import '../src/loadAppEnv.js';
import { createConnectionStore, connectionBinding } from '../src/accountConnections.js';
import { createPluginSessions, ensurePluginSchema } from '../src/pluginSessions.js';

const qa = process.env.DB_NAME === 'quickcaption_qa' && process.env.DB_USER === 'quickcaption_qa';
test('QA: browser and plugin isolation, revocation, refreshed token replay, unknown logins, pairing races and media grants', { skip: !qa }, async t => {
  const { default: pool, upsertUser } = await import('../db.js');
  await ensurePluginSchema(pool);
  const uid = `qa-connections-${randomUUID()}`, otherUid = `qa-connections-${randomUUID()}`;
  const links = [];
  t.after(async () => {
    for (const id of links) await pool.execute('DELETE FROM plugin_links WHERE id = ?', [id]);
    await pool.execute('DELETE d FROM plugin_connection_details d JOIN plugin_sessions p ON p.id = d.id WHERE p.user_uid IN (?, ?)', [uid, otherUid]);
    await pool.execute('DELETE FROM browser_connections WHERE user_uid IN (?, ?)', [uid, otherUid]);
    await pool.execute('DELETE FROM account_connection_state WHERE user_uid IN (?, ?)', [uid, otherUid]);
    await pool.execute('DELETE FROM users WHERE uid IN (?, ?)', [uid, otherUid]);
    await pool.end();
  });
  await upsertUser({ uid, email: 'connections@example.invalid' });
  await upsertUser({ uid: otherUid, email: 'other-connections@example.invalid' });
  const store = createConnectionStore(pool), plugins = createPluginSessions(pool);
  const now = Math.floor(Date.now() / 1000);
  const identity = { uid, email: 'connections@example.invalid', authTime: now - 100 };
  const current = await store.browser(identity, 'Windows Chrome/150.0');
  const second = await store.browser({ ...identity, authTime: now - 90 }, 'iPhone Safari/604.1');
  const outsider = await store.browser({ uid: otherUid, authTime: now - 80 }, 'Windows Firefox/150');
  assert.equal((await store.browser(identity, 'changed')).browserConnectionId, current.browserConnectionId, 'Refreshed Firebase token retains its login identity');
  await assert.rejects(store.revoke(uid, outsider.browserConnectionId), { status: 404 });
  assert.equal((await store.list(otherUid, outsider.browserConnectionId)).length, 1);
  const link = await plugins.start(); links.push(link.id);
  await plugins.approve(link.id, link.userCode, identity);
  const paired = await plugins.poll(link.id, link.deviceSecret);
  const plugin = await plugins.verify(paired.accessToken);
  const list = await store.list(uid, current.browserConnectionId);
  assert.equal(list.length, 3); assert.equal(list.filter(item => item.current).length, 1);
  assert.equal(list.find(item => item.kind === 'premiere').label, 'Premiere Pro');
  assert.ok(!JSON.stringify(list).includes(paired.accessToken));
  const browserGrant = { userUid: uid, ...connectionBinding(second) };
  const pluginGrant = { userUid: uid, ...connectionBinding(plugin) };
  assert.equal(await store.grantActive(browserGrant), true);
  const deniedPairing = await plugins.start(); links.push(deniedPairing.id);
  await plugins.approve(deniedPairing.id, deniedPairing.userCode, { ...identity, authTime: now - 90 });
  await store.revoke(uid, second.browserConnectionId);
  await assert.rejects(plugins.poll(deniedPairing.id, deniedPairing.deviceSecret), { code: 'CONNECTION_REVOKED' }, 'A revoked browser cannot complete an earlier pending pairing');
  await assert.rejects(store.browser({ ...identity, authTime: now - 90 }, 'new user-agent'), { code: 'CONNECTION_REVOKED' });
  assert.equal(await store.grantActive(browserGrant), false);
  assert.equal((await store.browser(identity)).browserConnectionId, current.browserConnectionId);
  await store.revoke(uid, plugin.pluginSessionId);
  assert.equal(await plugins.verify(paired.accessToken), null);
  await assert.rejects(plugins.refresh(paired.refreshToken), { status: 401 });
  assert.equal(await store.grantActive(pluginGrant), false);
  assert.equal(await store.grantActive({ userUid: uid }), false, 'Legacy unbound media cannot bypass revocation');
  const pending = await plugins.start(); links.push(pending.id);
  await plugins.approve(pending.id, pending.userCode, identity);
  await store.revokeAll(uid);
  await assert.rejects(store.browser(identity), { code: 'CONNECTION_REVOKED' });
  await assert.rejects(store.browser({ ...identity, authTime: now - 70 }), { code: 'CONNECTION_REVOKED' }, 'An old unregistered browser is also blocked');
  await assert.rejects(plugins.poll(pending.id, pending.deviceSecret), { status: 410 });
  assert.equal((await store.list(uid)).length, 0);
  assert.equal((await store.browser({ uid: otherUid, authTime: now - 80 })).browserConnectionId, outsider.browserConnectionId);
  const [state] = await pool.execute('SELECT revoked_before FROM account_connection_state WHERE user_uid = ?', [uid]);
  // Inject a later verified login time to test a fresh sign-in without real Google credentials.
  const fresh = await store.browser({ ...identity, authTime: Number(state[0].revoked_before) + 1 });
  assert.equal(await store.grantActive({ userUid: uid, ...connectionBinding(fresh) }), true);
  const race = await plugins.start(); links.push(race.id);
  await plugins.approve(race.id, race.userCode, { ...identity, authTime: Number(state[0].revoked_before) + 1 });
  await Promise.allSettled([plugins.poll(race.id, race.deviceSecret), store.revokeAll(uid)]);
  // A transaction deadlock can abort one operation; finish the revocation once.
  await store.revokeAll(uid);
  assert.equal((await store.list(uid)).length, 0);
});
