import test from 'node:test';
import assert from 'node:assert/strict';
import mysql from 'mysql2/promise';
import { randomUUID } from 'node:crypto';
import { ADMIN_TABLES, ensureAdminSchema, createAdminStore } from '../src/adminStore.js';
import { createDownloadStore } from '../src/downloadStore.js';

test('MySQL download records, per-user statistics and feedback survive media retention', { skip: process.env.RUN_MYSQL_TESTS !== '1' }, async t => {
  await import('../src/loadAppEnv.js');
  const db = await mysql.createConnection({ host: process.env.DB_HOST, user: process.env.DB_USER, password: process.env.DB_PASSWORD, database: process.env.DB_NAME, connectTimeout: 10000 });
  t.after(() => db.end());
  await db.execute(`CREATE TEMPORARY TABLE users (id INT PRIMARY KEY, uid VARCHAR(128) UNIQUE, email VARCHAR(255), display_name VARCHAR(255), credits INT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`);
  await db.execute(`CREATE TEMPORARY TABLE videos (id INT PRIMARY KEY, user_uid VARCHAR(128), original_filename VARCHAR(255), media_type VARCHAR(16), duration_seconds INT, subtitle_json JSON, status VARCHAR(16), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`);
  await db.execute(`CREATE TEMPORARY TABLE credit_payments (user_uid VARCHAR(128), amount_usd DECIMAL(10,2)) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci`);
  for (const sql of ADMIN_TABLES) await db.execute(sql.replace('CREATE TABLE IF NOT EXISTS', 'CREATE TEMPORARY TABLE'));
  await db.execute("INSERT INTO users (id, uid, email, display_name, credits) VALUES (1, 'owner', 'owner@example.com', 'Owner', 50), (2, 'other', 'other@example.com', 'Other', 50)");
  await db.execute("INSERT INTO videos (id, user_uid, original_filename, media_type, duration_seconds, status) VALUES (42, 'owner', 'סרטון.mp4', 'video', 60, 'completed'), (43, 'owner', 'failed.mp4', 'video', 0, 'failed'), (44, 'owner', 'audio.mp3', 'audio', 30, 'completed')");
  const schemaDb = { execute: (sql, params) => db.execute(sql.replace(/^CREATE TABLE IF NOT EXISTS/, 'CREATE TEMPORARY TABLE IF NOT EXISTS'), params) };
  await ensureAdminSchema(schemaDb); await ensureAdminSchema(schemaDb);
  const downloads = createDownloadStore(db), admin = createAdminStore(db);
  const event = { id: randomUUID(), userUid: 'owner', videoId: 42, kind: 'video', format: 'mp4' };
  await downloads.recordDownload(event); await downloads.recordDownload(event);
  await assert.rejects(downloads.recordDownload({ ...event, userUid: 'other' }), { status: 404 });
  await assert.rejects(downloads.recordDownload({ ...event, videoId: 43 }), { status: 404 });
  await assert.rejects(downloads.recordDownload({ ...event, videoId: 44 }), { status: 404 });
  await assert.rejects(downloads.recordDownload({ ...event, kind: 'subtitles', format: 'srt' }), { status: 409 });
  await downloads.recordDownload({ ...event, id: randomUUID() });
  await downloads.recordDownload({ ...event, id: randomUUID(), kind: 'subtitles', format: 'vtt' });
  const audioId = randomUUID();
  await downloads.recordDownload({ ...event, id: audioId, videoId: 44, kind: 'subtitles', format: 'txt' });
  await downloads.saveFeedback({ downloadId: audioId, userUid: 'owner', rating: 4, feedback: '' });
  await assert.rejects(downloads.saveFeedback({ downloadId: audioId, userUid: 'other', rating: 5, feedback: '' }), { status: 404 });
  const feedback = { downloadId: event.id, userUid: 'owner', rating: 4, feedback: 'חוויה טובה\nתודה!' };
  await downloads.saveFeedback(feedback); await downloads.saveFeedback(feedback);
  await assert.rejects(downloads.saveFeedback({ ...feedback, userUid: 'other' }), { status: 404 });
  await db.execute('DELETE FROM videos');
  const stats = await admin.overview();
  assert.equal(Number(stats.uploads.videos), 2); assert.equal(Number(stats.uploads.audio), 1);
  assert.equal(Number(stats.downloads.videos), 2); assert.equal(Number(stats.downloads.subtitles), 2); assert.equal(Number(stats.downloads.uniqueVideos), 1);
  assert.equal(Number(stats.feedback.count), 2); assert.equal(Number(stats.feedback.averageRating), 4);
  const owner = (await admin.users('owner', 0)).users[0];
  assert.equal(Number(owner.uploadedVideos), 2); assert.equal(Number(owner.videoDownloads), 2); assert.equal(Number(owner.subtitleDownloads), 2); assert.equal(Number(owner.averageRating), 4);
  assert.equal(Number(owner.downloadedVideos), 1);
  const other = (await admin.users('other', 0)).users[0];
  assert.equal(Number(other.uploadedVideos), 0); assert.equal(Number(other.videoDownloads), 0); assert.equal(other.averageRating, null);
  assert.equal(Number(other.downloadedVideos), 0);
  const page = await downloads.feedback(0);
  assert.equal(page.total, 2);
  const videoFeedback = page.feedback.find(entry => entry.id === event.id);
  assert.equal(videoFeedback.filename, 'סרטון.mp4'); assert.equal(videoFeedback.feedback, feedback.feedback);
  await downloads.recordDownload({ ...event, id: randomUUID() }); // A cached export still belongs to its original owner.
});
