// Generated by scripts/build-premiere-shared.mjs; edit premiere-plugin/caption-timing.js.
// Repair model point cues before creating native clips. Keep every spoken word.
function normalizeCaptionTiming(value, duration, minimum = .04) {
  const rows = typeof value === 'string' ? JSON.parse(value) : value;
  if (!Array.isArray(rows)) throw new Error('Missing captions');
  const captions = rows.map(row => ({ ...row }));
  for (let i = 0; i < captions.length; i++) {
    const cue = captions[i];
    if (!Number.isFinite(cue.start) || cue.start !== cue.end || typeof cue.text !== 'string' || !cue.text.trim()) continue;
    const previous = captions[i - 1], next = captions[i + 1];
    const right = Math.min(duration, next?.start ?? duration), left = Math.max(0, previous?.end ?? 0);
    if (right - cue.start >= minimum) cue.end = Math.min(right, cue.start + .3);
    else if (cue.start - left >= minimum) cue.start = Math.max(left, cue.start - .3);
    else if (previous?.end === cue.start && previous.end > previous.start) {
      previous.text = previous.text.trimEnd() + ' ' + cue.text.trim(); captions.splice(i--, 1);
    } else if (next?.start === cue.end && next.end > next.start) {
      next.text = cue.text.trim() + ' ' + next.text.trimStart(); captions.splice(i--, 1);
    }
  }
  return captions;
}
module.exports = { normalizeCaptionTiming };
