import type { Segment, Word } from "./client/types";
export type CaptionMotion = "none" | "pop";
export type PopIntensity = "gentle" | "strong";
export function sanitizeCaptionMotion(value: unknown): CaptionMotion;
export function sanitizePopIntensity(value: unknown): PopIntensity;
export function popPeakScale(intensity?: PopIntensity): number;
export function wordPopCues(words: Word[]): Word[];
export function popKeyframes(durationSeconds: number, intensity?: PopIntensity): { time: number; scale: number }[];
export function wordPopScale(word: Word, currentTime: number, intensity?: PopIntensity): number;
export function escapeAssText(text: string): string;
export function renderWordPopAss(segments: Segment[], sourceWords: Word[], options?: { intensity?: PopIntensity; direction?: "rtl" | "ltr"; videoWidth?: number; videoHeight?: number; outlineWidth?: number }): string;
